@startuml

interface Cluster{
    + <T> Invoker<T> join(Directory<T> directory)
}

class AvailableCluster implements Cluster {
}

class FailfastCluster implements Cluster {
}

class FailoverCluster implements Cluster {
}

class MockClusterWrapper implements Cluster {
}


abstract class AbstractClusterInvoker<T> implements Invoker
class FailfastClusterInvoker<T> extends AbstractClusterInvoker
class FailoverClusterInvoker<T> extends AbstractClusterInvoker
class MockClusterInvoker<T> implements Invoker



AvailableCluster *-- AbstractClusterInvoker
FailfastCluster *-- FailfastClusterInvoker
FailoverCluster *-- FailoverClusterInvoker
MockClusterWrapper *-- MockClusterInvoker


@enduml