@startuml

interface Exporter<T> {
    + Invoker<T> getInvoker()
    + void unexport()
}

abstract class AbstractExporter<T> implements Exporter {
    - Invoker<T> invoker
    + Invoker<T> getInvoker()
    + void unexport()
}

class InjvmExporter<T> extends AbstractExporter {
    + void unexport()
}

class DubboExporter<T> extends AbstractExporter {
    + void unexport()
}
@enduml